//*****************************************************************************
// pinmux.c 
// 
// Configure the device pins for different peripheral signals
// 
// Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/ 
// 
// 
//  Redistribution and use in source and binary forms, with or without 
//  modification, are permitted provided that the following conditions 
//  are met:
//
//    Redistributions of source code must retain the above copyright 
//    notice, this list of conditions and the following disclaimer.
//
//    Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the 
//    documentation and/or other materials provided with the   
//    distribution.
//
//    Neither the name of Texas Instruments Incorporated nor the names of
//    its contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
//  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
//  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
//  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
//  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
//  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
//  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
//  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
//  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
//  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//*****************************************************************************

//*****************************************************************************
// This file was automatically generated by the CC32xx PinMux Utility
// by TI PinMux version 3.0.334
//
//*****************************************************************************

#include "pinmux.h"
#include "hw_types.h"
#include "hw_memmap.h"
#include "hw_gpio.h"
#include "pin.h"
#include "rom.h"
#include "rom_map.h"
#include "gpio.h"
#include "prcm.h"
#include "utils.h"

#if 1
void PinMuxConfig_for_Camera(void)
{
    //
    // Enable Peripheral Clocks 
    //
    MAP_PRCMPeripheralClkEnable(PRCM_CAMERA, PRCM_RUN_MODE_CLK);
    MAP_PRCMPeripheralClkEnable(PRCM_I2CA0, PRCM_RUN_MODE_CLK);

    //
    // Configure PIN_55 for CAMERA0 CAM_pCLK
    //
    MAP_PinTypeCamera(PIN_55, PIN_MODE_4);

    //
    // Configure PIN_58 for CAMERA0 CAM_pDATA7
    //
    MAP_PinTypeCamera(PIN_58, PIN_MODE_4);

    //
    // Configure PIN_59 for CAMERA0 CAM_pDATA6
    //
    MAP_PinTypeCamera(PIN_59, PIN_MODE_4);

    //
    // Configure PIN_60 for CAMERA0 CAM_pDATA5
    //
    MAP_PinTypeCamera(PIN_60, PIN_MODE_4);

    //
    // Configure PIN_61 for CAMERA0 CAM_pDATA4
    //
    MAP_PinTypeCamera(PIN_61, PIN_MODE_4);

    //
    // Configure PIN_02 for CAMERA0 CAM_pXCLK
    //
    MAP_PinTypeCamera(PIN_02, PIN_MODE_4);

    //
    // Configure PIN_03 for CAMERA0 CAM_vS
    //
    MAP_PinTypeCamera(PIN_03, PIN_MODE_4);

    //
    // Configure PIN_04 for CAMERA0 CAM_hS
    //
    MAP_PinTypeCamera(PIN_04, PIN_MODE_4);

    //
    // Configure PIN_05 for CAMERA0 CAM_pDATA8
    //
    MAP_PinTypeCamera(PIN_05, PIN_MODE_4);

    //
    // Configure PIN_06 for CAMERA0 CAM_pDATA9
    //
    MAP_PinTypeCamera(PIN_06, PIN_MODE_4);

    //
    // Configure PIN_07 for CAMERA0 CAM_pDATA10
    //
    MAP_PinTypeCamera(PIN_07, PIN_MODE_4);

    //
    // Configure PIN_08 for CAMERA0 CAM_pDATA11
    //
    MAP_PinTypeCamera(PIN_08, PIN_MODE_4);

    //
    // Configure PIN_16 for I2C0 I2C_SCL
    //
    MAP_PinTypeI2C(PIN_16, PIN_MODE_9);

    //
    // Configure PIN_17 for I2C0 I2C_SDA
    //
    MAP_PinTypeI2C(PIN_17, PIN_MODE_9);


    // GPIO_07   PIN62  ---camera-reset 控制脚
    MAP_PinTypeGPIO(PIN_62, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA0_BASE, 0x80, GPIO_DIR_MODE_OUT);

    // GPIO_02   PIN57  ---camera-pwdn 控制脚
    MAP_PinTypeGPIO(PIN_57, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA0_BASE, 0x04, GPIO_DIR_MODE_OUT);
}

void PinMuxConfig_for_Uart1(void)   
{
#ifdef UART1_PRINTF  
    //
    // Enable Peripheral Clocks 
    //
    MAP_PRCMPeripheralClkEnable(PRCM_UARTA1, PRCM_RUN_MODE_CLK);

    //-------------------------------------------------
    //
    // Configure PIN_01 for MODE7 UART1_TX
    //
    MAP_PinTypeUART(PIN_01, PIN_MODE_7);
#endif  
}
#endif


#if defined(HAL_OLED)    
void PinMuxConfig_for_LCD(void)
{
    // Enable Peripheral Clocks 
    //
    MAP_PRCMPeripheralClkEnable(PRCM_GPIOA0, PRCM_RUN_MODE_CLK);
    MAP_PRCMPeripheralClkEnable(PRCM_GPIOA1, PRCM_RUN_MODE_CLK);
    MAP_PRCMPeripheralClkEnable(PRCM_GPIOA3, PRCM_RUN_MODE_CLK);

    // oled 显示屏的 D0 信号线
    // Configure PIN_50(gpio_00) for GPIOOutput 
    MAP_PinTypeGPIO(PIN_50, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA0_BASE, 0x1, GPIO_DIR_MODE_OUT);

    // oled 显示屏的 D1 信号线
    // Configure PIN_63(gpio_08) for GPIOOutput 
    MAP_PinTypeGPIO(PIN_63, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA1_BASE, 0x1, GPIO_DIR_MODE_OUT);

    // oled 显示屏的 RST 信号线
    // Configure PIN_18(gpio_28) for GPIOOutput
    MAP_PinTypeGPIO(PIN_18, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA3_BASE, 0x10, GPIO_DIR_MODE_OUT);   

    // oled 显示屏的 DC 信号线
    // Configure PIN_45(gpio_31) for GPIOOutput
    MAP_PinTypeGPIO(PIN_45, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA3_BASE, 0x80, GPIO_DIR_MODE_OUT);    
}
#endif   


#if defined(HAL_LED)    
void PinMuxConfig_for_LED(void)
{
    // Enable Peripheral Clocks 
    //
    MAP_PRCMPeripheralClkEnable(PRCM_GPIOA1, PRCM_RUN_MODE_CLK);

    // D7 led灯
    // Configure PIN_64(gpio_09) for GPIOOutput
    MAP_PinTypeGPIO(PIN_64, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA1_BASE, 0x02, GPIO_DIR_MODE_OUT);    


    // D6 led灯
    // Configure PIN_01(gpio_10) for GPIOOutput
    MAP_PinTypeGPIO(PIN_01, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA1_BASE, 0x04, GPIO_DIR_MODE_OUT);    

    // D5 led灯
    // Configure PIN_02(gpio_11) for GPIOOutput
    MAP_PinTypeGPIO(PIN_02, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA1_BASE, 0x08, GPIO_DIR_MODE_OUT);    

}
#endif   



// CAEMRA_PWDN 为 PIN_57， 也就是gpio02
void GPIO_SET_CAMERA_PWDN(unsigned char outValue)
{
    if(outValue)
    {
        MAP_GPIOPinWrite(GPIOA0_BASE,GPIO_PIN_2,GPIO_PIN_2);
    }

    else
    {
        MAP_GPIOPinWrite(GPIOA0_BASE,GPIO_PIN_2,0);
    }
}

// CAEMRA_RESET 为 PIN_62， 也就是gpio07
void GPIO_SET_CAMERA_RESET(unsigned char outValue)
{
    if(outValue)
    {
        MAP_GPIOPinWrite(GPIOA0_BASE,GPIO_PIN_7,GPIO_PIN_7);
    }

    else
    {
        MAP_GPIOPinWrite(GPIOA0_BASE,GPIO_PIN_7,0);
    }
}



#if defined(HAL_OLED)
// clk 为 PIN_50， 也就是gpio00
void GPIO_SET_CLK(unsigned char dat)
{
    if(dat)
    {
        MAP_GPIOPinWrite(GPIOA0_BASE,GPIO_PIN_0,GPIO_PIN_0);
    }
    else
    {
        MAP_GPIOPinWrite(GPIOA0_BASE,GPIO_PIN_0,0);
    }
}

// dat 为 PIN_63， 也就是gpio08
void GPIO_SET_DAT(unsigned char dat)
{
    if(dat)
    {
        MAP_GPIOPinWrite(GPIOA1_BASE,GPIO_PIN_0,GPIO_PIN_0);
    }
    else
    {
        MAP_GPIOPinWrite(GPIOA1_BASE,GPIO_PIN_0,0);
    }
}

// rst 为 PIN_64， 也就是gpio9
void GPIO_SET_RST(unsigned char dat)
{
    if(dat)
    {
//        MAP_GPIOPinWrite(GPIOA1_BASE,GPIO_PIN_1,GPIO_PIN_1);
        MAP_GPIOPinWrite(GPIOA3_BASE,GPIO_PIN_4,GPIO_PIN_4);
    }
    else
    {
//        MAP_GPIOPinWrite(GPIOA1_BASE,GPIO_PIN_1,0);
        MAP_GPIOPinWrite(GPIOA3_BASE,GPIO_PIN_4,0);
    }
}

// dc 为 PIN_01， 也就是gpio10
void GPIO_SET_DC(unsigned char dat)
{
    if(dat)
    {
//        MAP_GPIOPinWrite(GPIOA1_BASE,GPIO_PIN_2,GPIO_PIN_2);
        MAP_GPIOPinWrite(GPIOA3_BASE,GPIO_PIN_7,GPIO_PIN_7);
    }
    else
    {
//        MAP_GPIOPinWrite(GPIOA1_BASE,GPIO_PIN_2,0);
        MAP_GPIOPinWrite(GPIOA3_BASE,GPIO_PIN_7,0);
    }
}
#endif

#if defined(HAL_KEY)
unsigned char Key_Get_if_SW2_Pressed()
{
    long ulKeyVal = MAP_GPIOPinRead(GPIOA2_BASE,GPIO_PIN_6);
    if(ulKeyVal)
        return 1;
    else
        return 0;
}

unsigned char Key_Get_if_SW3_Pressed()
{
    long ulKeyVal = MAP_GPIOPinRead(GPIOA1_BASE,GPIO_PIN_5);
    if(ulKeyVal)
        return 1;
    else
        return 0;
}
#endif
