//****************************************************************************
// pinmux.h 
// 
// Header file for pinmuxconfig
// 
// Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/ 
// 
// 
//  Redistribution and use in source and binary forms, with or without 
//  modification, are permitted provided that the following conditions 
//  are met:
//
//    Redistributions of source code must retain the above copyright 
//    notice, this list of conditions and the following disclaimer.
//
//    Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the 
//    documentation and/or other materials provided with the   
//    distribution.
//
//    Neither the name of Texas Instruments Incorporated nor the names of
//    its contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
//  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
//  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
//  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
//  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
//  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
//  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
//  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
//  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
//  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//*****************************************************************************

//*****************************************************************************
// This file was automatically generated by the CC32xx PinMux Utility
// by TI PinMux version 3.0.334
//
//*****************************************************************************

#ifndef __PINMUX_H__
#define __PINMUX_H__

extern void PinMuxConfig_for_Camera(void);
extern void PinMuxConfig_for_Uart1(void);  
extern void PinMuxConfig_for_LCD(void);
extern void PinMuxConfig_for_LED(void);

extern void GPIO_SET_CAMERA_RESET(unsigned char outValue);
extern void GPIO_SET_CAMERA_PWDN(unsigned char outValue);

#if defined(HAL_OLED)
extern void GPIO_SET_CLK(unsigned char dat);
extern void GPIO_SET_DAT(unsigned char dat);
extern void GPIO_SET_RST(unsigned char dat);
extern void GPIO_SET_DC(unsigned char dat);
#endif

#if defined(HAL_KEY)
extern unsigned char Key_Get_if_SW2_Pressed();
extern unsigned char Key_Get_if_SW3_Pressed();
#endif

#endif //  __PINMUX_H__
